### ISSUE TITLE
Changing background color of the navigation bar

### ISSUE THREAD

**Issue by nim23** [iSimar/HackerNews-React-Native#1]
Hi, 

Just wanted to ask a quick question about whether you were able to change the background color of the navigation bar. I did try using barTintColor but to no avail.

Thanks,
Nimesj

**Comment by iSimar** [comment]
Hello Nimesj,

After checking the source code for NavigatorIOS, it seems that barTintColor is a valid attribute (Line 49), but I think they still have to implement/fix that functionality. I suggest you point out this issue on the main repository.

Source code for NavigatorIOS:
https://github.com/facebook/react-native/blob/72d3d724a3a0c6bc46981efd0dad8f7f61121a47/Libraries/Components/Navigation/NavigatorIOS.ios.js
