### ISSUE TITLE
Upgrading to React Native 0.16

### ISSUE THREAD

**Issue by iSimar** [iSimar/HackerNews-React-Native#16]
@ivanph I'm currently trying to upgrade the app with react native 0.16 under the `react-native-0_16` branch, could you confirm if everything is fine with android

**Comment by ivanph** [comment]
Hi @iSimar 

The following folders are missing 
>android/app/src/main/res/drawable-hdpi/
	android/app/src/main/res/drawable-mdpi/
	android/app/src/main/res/drawable-xhdpi/
	android/app/src/main/res/drawable-xxhdpi/
	android/app/src/main/res/drawable-xxxhdpi/

They contain the navigation icon for the toolbar in different sizes. 
Also package.json is missing the `react-native-webintent` module that is used to open the posts links. 
Maybe you could create a PR and we can discuss the changes there. 
Cheers.

**Comment by iSimar** [comment]
I tried upgrading react native to 0.16 with package.json & npm install but it broke a bunch of stuff, so I had to react-native init a new project and copy over the stuff manually.

I have added the missing stuff you mentioned above just now. I did not add `react-native-webintent` because I think it would be better to upgrade to `IntentAndroid`. See commit [6e52dcb](https://github.com/iSimar/HackerNews-React-Native/commit/6e52dcb460ddb0b6145c63a32995db910c8376c5)

**Comment by ivanph** [comment]
I created a [branch](/ivanph/HackerNews-React-Native/commits/v0.16) with the upgrade to version 0.16 and replaced the webintent module with IntentAndroid.
It might be easier if we merge that branch first and then you could add your changes on top.

**Comment by amilajack** [comment]
<img width="524" alt="screen shot 2015-12-14 at 2 25 29 pm" src="https://cloud.githubusercontent.com/assets/6374832/11796006/bd96782c-a26e-11e5-8209-b7c0946beaab.png">

I'm getting this error when I checked out the branch and installed dependencies

**Comment by iSimar** [comment]
@amilajack I don't seem to be getting  that error after cloning/checking-out the branch. Try pulling the new commits see if you're getting the same error.

**Comment by johntom** [comment]
Hi,
Tried Android on win10 running node v4.2.1 with npm 3.5.2
1) If I just try a git clone with repo iSimar or ivanph I cant get npm install to run 
2) I created a sep directory with react-native init HackerNewsReactNative
3) I then copied package.json, index.android.js and app dir but get "unable to download js bundle error." on my emulator which does show the hacker icon.
John

**Comment by iSimar** [comment]
@johntom I'm unaware of this issue, I will try to look into it.

@ivanph I'm actually recoding most of the app, I don't think that would be necessary

**Comment by iSimar** [comment]
The master has been updated.
