### ISSUE TITLE
Android Links

### ISSUE THREAD

**Issue by johntom** [iSimar/HackerNews-React-Native#21]
Hi,
A blank page displays when I press source link from index.android.js. I verifed the same behavior in a separate app.
Thanks,
John

**Comment by iSimar** [comment]
Hello John, 

Sorry for the delay. That issue has been fixed. The project has been updated to react-native v0.20 and the android app includes new features.

Kind Regards,
Simar

**Comment by iSimar** [comment]
Android app is also available on the play store as a demo
https://play.google.com/store/apps/details?id=com.hackernews
