### ISSUE TITLE
 Could not find property 'MYAPP_RELEASE_STORE_PASSWORD' 

### ISSUE THREAD

**Issue by ws123** [iSimar/HackerNews-React-Native#28]
* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find property 'MYAPP_RELEASE_STORE_PASSWORD' on SigningConfig_Decorated{name=release, storeFile=/home/carlos/react-native/HackerNews-React-Native/android/app/hn-reader_android.keystore, storePassword=null, keyAlias=null, keyPassword=null, storeType=/home/carlos/react-native/HackerNews-React-Native/android/app/hn-reader_android.keystore}.

**Comment by stevefermi** [comment]
You have to set it to a specific string, it's something like
```
keyPassword '12345678'
```

I think the author may forget to write it down.

**Comment by wrexem** [comment]
I commented that section out in build.gradle (HackerNews-React-Native\android\app\build.gradle)

Basically, they are intentionally removing their keys from the versions pushed to github.

    signingConfigs {
        release {
            /*
	    storeFile file('hn-reader_android.keystore')
            storePassword MYAPP_RELEASE_STORE_PASSWORD
            keyAlias MYAPP_RELEASE_KEY_ALIAS
            keyPassword MYAPP_RELEASE_KEY_PASSWORD
	    */
        }
    }

**Comment by ws123** [comment]
thank you
