### ISSUE TITLE
Content doesn't update

### ISSUE THREAD

**Issue by ccheever** [iSimar/HackerNews-React-Native#4]
Hi-

I was playing around with this app, and I wanted to promote it on this gallery that @ide and I are working on (http://exp.host/). I got everything working, but the content doesn't update -- all the stories are from a few weeks ago.

I think the issue is with the Kimono Labs endpoint you're using. When I load the URL https://www.kimonolabs.com/api/d3rpj7om , part of the response is ...`"frequency":"Manual Crawl","`... which made me think it might be configured in a way that you have to manually run the updates?

Is there any way we could fix this up so that the content updates every 15 minutes or something like that?

**Comment by iSimar** [comment]
Hello, 

The content will update every hour now. Kimonolabs doesn't provide a crawling option for every 15 minutes. 

Regards,

**Comment by ccheever** [comment]
Very cool. Thank you.
