### ISSUE TITLE
Could not find property 'MYAPP_RELEASE_STORE_PASSWORD'

### ISSUE THREAD

**Issue by pikapoo92** [iSimar/HackerNews-React-Native#49]
Can't get to build due to this particular error - how do I fix this?

FAILURE: Build failed with an exception.

* Where:
Build file '/home/devyn/Documents/KeaganProjects/HackerNews-React-Native/android/app/build.gradle' line: 95

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find property 'MYAPP_RELEASE_STORE_PASSWORD' on SigningConfig_Decorated{name=release, storeFile=/home/devyn/Documents/KeaganProjects/HackerNews-React-Native/android/app/hn-reader_android.keystore, storePassword=null, keyAlias=null, keyPassword=null, storeType=/home/devyn/Documents/KeaganProjects/HackerNews-React-Native/android/app/hn-reader_android.keystore}.

**Comment by beast02** [comment]
Same problem !!
> FAILURE: Build failed with an exception.
> 
>     * Where:
>       Build file '/home/devyn/Documents/KeaganProjects/HackerNews-React-Native/android/app/build.gradle' line: 95
> 
>     * What went wrong:
>       A problem occurred evaluating project ':app'.
> 
> 
> > Could not find property 'MYAPP_RELEASE_STORE_PASSWORD' on SigningConfig_Decorated{name=release, storeFile=/home/devyn/Documents/KeaganProjects/HackerNews-React-Native/android/app/hn-reader_android.keystore, storePassword=null, keyAlias=null, keyPassword=null, storeType=/home/devyn/Documents/KeaganProjects/HackerNews-React-Native/android/app/hn-reader_android.keystore}.
