### ISSUE TITLE
Is this in the appstore?

### ISSUE THREAD

**Issue by bnolan** [iSimar/HackerNews-React-Native#5]
It'd be great if this was in the appstore so we could try it out. It's hard to find what react native apps are in the appstore and this one looks like a good one. :)

**Comment by iSimar** [comment]
I haven't bought the apple's developer account, but I do plan on getting it soon. If no one puts it on the app store by then I guess I'ill do it.

**Comment by cheeaun** [comment]
Would be cool if this could work or listed in [React Native Playground](https://rnplay.org/) too :smile:

**Comment by iSimar** [comment]
App is available  on the app store. 
https://itunes.apple.com/ca/app/hacker-news-reader-react-native/id1067161633?mt=8

**Comment by iSimar** [comment]
The android version of the app is now available on Google Play Store.
https://play.google.com/store/apps/details?id=com.hackernews
