### ISSUE TITLE
Android Port 

### ISSUE THREAD

**Issue by ivanph** [iSimar/HackerNews-React-Native#6]
Hi,
I added an android version to your app and thought I'll ask before sending a PR. You can take a look here https://github.com/ivanph/HackerNews-React-Native/tree/android_port. I was able to make it work for both platforms from the same code-base. Let me know if you are interested and I'll send the PR.

Thanks.

**Comment by iSimar** [comment]
Hey Ivan, great work. 
Can you use the nexus 4 as the mock up for the screenshots:
http://mockuphone.com/nexus4

Just line up 3 of them under the Android Screenshots heading.

**Comment by iSimar** [comment]
And yeah you can send the PR :+1:

**Comment by ivanph** [comment]
Cool, I'll update the screenshots and send the PR.
